/*
 * Follow this format:
 * export const YOUR_ACTION_CONSTANT = '<component-path>/YOUR_ACTION_CONSTANT';
 */

export const REDUCER_KEY = 'playback';

export const ACTION_TYPES = {
  SET_CURRENT_RECORD_WITH_HISTORY: 'SET_CURRENT_RECORD_WITH_HISTORY',
  SET_SNAP_COMMENTS: 'SET_SNAP_COMMENTS',
  SET_CATEGORY_INDEX: 'SET_CATEGORY_INDEX',
  SET_RECORD_INDEX: 'SET_RECORD_INDEX',
  SET_HISTORY_INDEX: 'SET_HISTORY_INDEX',
};
