// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile =  {
    "aws_project_region": "us-east-1",
    // "aws_appsync_graphqlEndpoint": "https://7hiay4be35bi5b2jujxw4lkfmu.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_graphqlEndpoint": "https://l2ef6zhywnel3att32o53ns2ve.appsync-api.us-east-1.amazonaws.com/graphql",    
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS",
    // "aws_cognito_identity_pool_id": "us-east-1:ac3970c1-998e-44f5-b8e7-915b61c672dd",
    "aws_cognito_identity_pool_id": "us-east-1:08150bca-b94b-4b22-b34b-2b3cc4b4f2c8",
    "aws_cognito_region": "us-east-1",
    // "aws_user_pools_id": "us-east-1_iZaYY7v3Z",
    "aws_user_pools_id": "us-east-1_M8wfpyIKJ",
    // "aws_user_pools_web_client_id": "5doa5r4eeigmbvjmvo6475496a",
    "aws_user_pools_web_client_id": "nkjhni8fo530fjmdkgseadri5",
    "aws_content_delivery_bucket": "innovap3-js-exam-dev",
    "aws_content_delivery_bucket_region": "us-east-1",
    "aws_content_delivery_url": "http://innovap3-js-exam-dev.s3-website-us-east-1.amazonaws.com"
};


export default awsmobile;